### ISSUE TITLE
undefined method `+' for nil:NilClass (NoMethodError) (I'm a complete noob)

### ISSUE THREAD

**Issue by PiNh00fD** [mgarciap/cf-auto-scaling#5]
Hi, I installed bosh lite today and want to see what autoscaling does, so I pulled cf-auto-scaling, but when I run bundle exec ./bin/auto_scale.rb, I get an error:
undefined method `+' for nil:NilClass (NoMethodError)
I know nothing about ruby, so this doesn't mean any sense to me. please advise.

I'm also new to github, so I have no idea which information is needed to assist me in this matter.
Please help he to get underway in this new world. (like being on another planet)

Thnx in advance
AJ.

**Comment by mgarciap** [comment]
Hi AJ.
Sadly this app is not maintained any longer. There are newer alternatives
you can google.

**Comment by PiNh00fD** [comment]
oke, thnx for your swift response.
